[versions]
androidGradlePlugin = "9.0.1"
androidxAppcompat = "1.7.1"
androidxBenchmark = "1.4.1"
androidxCoreKtx = "1.17.0"
androidxTest = "1.7.0"
androidxTestExt = "1.3.0"
dagger = "2.54"
dokka = "2.0.0"
javaxInject = "1"
koin = "4.1.1"
kotlin = "2.3.10"
kotlinBinaryCompatibility = "0.18.1"
kotlinpoet = "2.2.0"
kotlinAtomicfu = "0.29.0"
ksp = "2.3.6"
mavenPublishPlugin = "0.32.0"

[libraries]
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidxAppcompat" }
androidx-benchmark-common = { group = "androidx.benchmark", name = "benchmark-common", version.ref = "androidxBenchmark" }
androidx-benchmark-junit4 = { group = "androidx.benchmark", name = "benchmark-junit4", version.ref = "androidxBenchmark" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidxCoreKtx" }
androidx-test-ext = { group = "androidx.test.ext", name = "junit-ktx", version.ref = "androidxTestExt" }
androidx-test-rules = { group = "androidx.test", name = "rules", version.ref = "androidxTest" }
androidx-test-runner = { group = "androidx.test", name = "runner", version.ref = "androidxTest" }
dagger = { group = "com.google.dagger", name = "dagger", version.ref = "dagger" }
dagger-compiler = { group = "com.google.dagger", name = "dagger-compiler", version.ref = "dagger" }
javax-inject = { group = "javax.inject", name = "javax.inject", version.ref = "javaxInject" }
koin-android = { group = "io.insert-koin", name = "koin-android", version.ref = "koin" }
kotlin-atomicfu = { group = "org.jetbrains.kotlinx", name = "atomicfu", version.ref = "kotlinAtomicfu" }
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotlin-test = { group = "org.jetbrains.kotlin", name = "kotlin-test", version.ref = "kotlin" }
kotlinpoet = { group = "com.squareup", name = "kotlinpoet", version.ref = "kotlinpoet" }
kotlinpoet-ksp = { group = "com.squareup", name = "kotlinpoet-ksp", version.ref = "kotlinpoet" }
ksp-api = { group = "com.google.devtools.ksp", name = "symbol-processing-api", version.ref = "ksp" }

# Dependencies of build-logic
android-gradle = { group = "com.android.tools.build", name = "gradle", version.ref = "androidGradlePlugin" }
dokka-gradle = { group = "org.jetbrains.dokka", name = "dokka-gradle-plugin", version.ref = "dokka" }
kotlin-gradle = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
maven-publish = { group = "com.vanniktech", name = "gradle-maven-publish-plugin", version.ref = "mavenPublishPlugin" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
kotlin-atomicfu-plugin = { id = "org.jetbrains.kotlinx.atomicfu", version.ref = "kotlinAtomicfu" }
kotlin-binary-compatibility = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version.ref = "kotlinBinaryCompatibility" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "mavenPublishPlugin" }

# Convention Plugins
stitch-android-library = { id = "stitch.android.library" }
stitch-jvm = { id = "stitch.jvm" }
stitch-publishing = { id = "stitch.publishing" }